baseurl = "https://astronautix.github.io/"
#baseurl = "https://localhost:1313/"
contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "../"
title = "CSEP"
canonifyurls  = true

DefaultContentLanguage = "fr"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true
math = true
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[markup.goldmark.renderer]
  unsafe= true

[languages]

  [languages.en]
    languageName= "En"
    subtitle = "The studient space center of École polytechnique"
    weight= 2
    
  [languages.fr]
    languageName= "Fr"
    subtitle = "Centre Spatial de l'École polytechnique, l'association étudiante qui envoie des satellites en obrite"
    weight= 1


[Params]
  logo = "img/logo_notext_whiteOnblue.png"
  favicon = "img/favicon.ico"
  # dateFormat = "January 2, 2006"
  commit = false
  # rss = true # for RSS flux
  comments = true
  
  [params.navigation]
    help = "Help"
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "Antoine Tavant"
  email = "antoine.tavant@polytechnique.edu"
  # facebook = "username"
  # googleplus = "+username" # or xxxxxxxxxxxxxxxxxxxxx
  gitlab = "astronautiX"
  github = "astronautiX"
  # twitter = "username"
  # reddit = "username"
  # linkedin = "username"
  # xing = "username"
  # stackoverflow = "users/XXXXXXX/username"
  # snapchat = "username"
  # instagram = "username"
  # youtube = "user/username" # or channel/channelname
  # soundcloud = "username"
  # spotify = "username"
  # bandcamp = "username"
  # itchio = "username"
  # keybase = "username"


[[menu.main]]
    name = "articles"
    url = "articles"
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3

# [[menu.main]]
#     identifier = "samples"
#     name = "Samples"
#     weight = 2
# 
# [[menu.main]]
#     parent = "samples"
#     name = "Big Image Sample"
#     url = "post/2017-03-07-bigimg-sample"
#     weight = 1
# 
# [[menu.main]]
#     parent = "samples"
#     name = "Math Sample"
#     url = "post/2017-03-05-math-sample"
#     weight = 2
# 
# [[menu.main]]
#     parent = "samples"
#     name = "Code Sample"
#     url = "post/2016-03-08-code-sample"
#     weight = 3

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3
    
    
    
[[menu.main]]
    name = "X-CubeSat"
    url = "articles/xcubesat"
    weight = 1
